flowchart LR
se:startevent:((startevent))-->a1:task:(需求部门经办人发起)
a1:task:(需求部门经办人发起)-->gw1s:exclusivegateway:{x}
gw1s:exclusivegateway:{x}-->gw2s:exclusivegateway:{x}
gw2s:exclusivegateway:{x}-->|"是"|a5:task:(需求部门资产管理员审批)
a5:task:(需求部门资产管理员审批)-->gw3s:exclusivegateway:{x}
gw3s:exclusivegateway:{x}-->gw4s:exclusivegateway:{x}
gw4s:exclusivegateway:{x}-->|"是"|a7:task:(归口管理部门经办人审批)
a7:task:(归口管理部门经办人审批)-->gw5s:exclusivegateway:{x}
gw5s:exclusivegateway:{x}-->gw6s:exclusivegateway:{x}
gw6s:exclusivegateway:{x}-->a13:task:(归口管理部门负责人审批)
a13:task:(归口管理部门负责人审批)-->gw7s:exclusivegateway:{x}
gw7s:exclusivegateway:{x}-->gw7e:exclusivegateway:{x}
gw7e:exclusivegateway:{x}-->gw6e:exclusivegateway:{x}
gw6s:exclusivegateway:{x}-->gw6e:exclusivegateway:{x}
gw6e:exclusivegateway:{x}-->gw5e:exclusivegateway:{x}
gw5s:exclusivegateway:{x}-->gw8s:exclusivegateway:{x}
gw8s:exclusivegateway:{x}-->a13:task:(归口管理部门负责人审批)
a13:task:(归口管理部门负责人审批)-->gw9s:exclusivegateway:{x}
gw9s:exclusivegateway:{x}-->gw9e:exclusivegateway:{x}
gw9e:exclusivegateway:{x}-->gw8e:exclusivegateway:{x}
gw8s:exclusivegateway:{x}-->gw8e:exclusivegateway:{x}
gw8e:exclusivegateway:{x}-->gw5e:exclusivegateway:{x}
gw5e:exclusivegateway:{x}-->gw4e:exclusivegateway:{x}
gw4s:exclusivegateway:{x}-->|"否"|a13:task:(归口管理部门负责人审批)
a13:task:(归口管理部门负责人审批)-->gw10s:exclusivegateway:{x}
gw10s:exclusivegateway:{x}-->gw10e:exclusivegateway:{x}
gw10e:exclusivegateway:{x}-->gw4e:exclusivegateway:{x}
gw4e:exclusivegateway:{x}-->gw3e:exclusivegateway:{x}
gw3s:exclusivegateway:{x}-->gw3e:exclusivegateway:{x}
gw3e:exclusivegateway:{x}-->gw2e:exclusivegateway:{x}
gw2s:exclusivegateway:{x}-->|"否"|a7:task:(归口管理部门经办人审批)
a7:task:(归口管理部门经办人审批)-->gw11s:exclusivegateway:{x}
gw11s:exclusivegateway:{x}-->gw12s:exclusivegateway:{x}
gw12s:exclusivegateway:{x}-->a13:task:(归口管理部门负责人审批)
a13:task:(归口管理部门负责人审批)-->gw13s:exclusivegateway:{x}
gw13s:exclusivegateway:{x}-->gw13e:exclusivegateway:{x}
gw13e:exclusivegateway:{x}-->gw12e:exclusivegateway:{x}
gw12s:exclusivegateway:{x}-->gw12e:exclusivegateway:{x}
gw12e:exclusivegateway:{x}-->gw11e:exclusivegateway:{x}
gw11s:exclusivegateway:{x}-->gw14s:exclusivegateway:{x}
gw14s:exclusivegateway:{x}-->a13:task:(归口管理部门负责人审批)
a13:task:(归口管理部门负责人审批)-->gw15s:exclusivegateway:{x}
gw15s:exclusivegateway:{x}-->gw15e:exclusivegateway:{x}
gw15e:exclusivegateway:{x}-->gw14e:exclusivegateway:{x}
gw14s:exclusivegateway:{x}-->gw14e:exclusivegateway:{x}
gw14e:exclusivegateway:{x}-->gw11e:exclusivegateway:{x}
gw11e:exclusivegateway:{x}-->gw2e:exclusivegateway:{x}
gw2e:exclusivegateway:{x}-->gw1e:exclusivegateway:{x}
gw1s:exclusivegateway:{x}-->gw1e:exclusivegateway:{x}
gw1e:exclusivegateway:{x}-->ee:endevent:((endevent))