graph LR
0:startevent:((startevent)) --> 1:task:(Experiences pain and immobility in right wrist)
1:task:(Experiences pain and immobility in right wrist) --> 2:task:(Decides to visit family doctor)
2:task:(Decides to visit family doctor) --> 3:task:(Travels to family doctor’s office)
3:task:(Travels to family doctor’s office) --> 4:subprocess:(Initial Medical Consultation)
4:subprocess:(Initial Medical Consultation) --> 5:task:("Perform medical history (anamnesis)")
5:task:("Perform medical history (anamnesis)") --> 6:task:(Perform physical examination)
6:task:(Perform physical examination) --> 7:task:(Document findings in paper patient record)
7:task:(Document findings in paper patient record) --> 8:exclusivegateway:{x}
8:exclusivegateway:{x} --> |NO| 9:task:(Diagnose bruise only)
8:exclusivegateway:{x} --> |YES| 10:task:(Ask about tetanus immunization status)
10:task:(Ask about tetanus immunization status) --> 11:exclusivegateway:{x}
11:exclusivegateway:{x} --> |YES| 13:task:(Issue referral for X-ray of right wrist)
11:exclusivegateway:{x} --> |NO| 12:task:(Administer tetanus booster)
12:task:(Administer tetanus booster) --> 13:task:(Issue referral for X-ray of right wrist)
13:task:(Issue referral for X-ray of right wrist) --> 14:task:(Patient leaves practice)
14:task:(Patient leaves practice) --> 15:task:(Calls radiology practices)
15:task:(Calls radiology practices) --> 16:task:(Finds available appointment next day)
16:task:(Finds available appointment next day) --> 17:task:(Travels to radiology practice)
17:task:(Travels to radiology practice) --> 18:subprocess:(Imaging and Reporting)
18:subprocess:(Imaging and Reporting) --> 19:task:(Register patient)
19:task:(Register patient) --> 20:task:(Collect data)
20:task:(Collect data) --> 21:task:("Perform X-ray (two views)")
21:task:("Perform X-ray (two views)") --> 22:task:(Store images on CD)
22:task:(Store images on CD) --> 23:task:(Hand out CD to patient)
23:task:(Hand out CD to patient) --> 24:task:(Announce findings)
24:task:(Announce findings) --> 25:exclusivegateway:{x}
25:exclusivegateway:{x} --> |NO| 26:endevent:(((endevent)))
25:exclusivegateway:{x} --> |YES| 27:task:(Radiologist calls patient)
27:task:(Radiologist calls patient) --> 28:task:(Receives phone call)
28:task:(Receives phone call) --> 29:task:(Decision: Attend trauma clinic same day)
29:task:(Decision: Attend trauma clinic same day) --> 30:task:(Travels to emergency department)
30:task:(Travels to emergency department) --> 31:subprocess:(Emergency Evaluation)
31:subprocess:(Emergency Evaluation) --> 32:task:(Patient waits)
32:task:(Patient waits) --> 33:task:(Trauma surgeon repeats)
33:task:(Trauma surgeon repeats) --> 34:exclusivegateway:{x}
34:exclusivegateway:{x} --> |YES| 36:task:(Attempt to open CD)
34:exclusivegateway:{x} --> |NO| 35:exclusivegateway:{x}
35:exclusivegateway:{x} --> |NO| 36:task:(Attempt to open CD)
35:exclusivegateway:{x} --> |YES| 36:task:(Attempt to open CD)
36:task:(Attempt to open CD) --> 37:exclusivegateway:{x}
37:exclusivegateway:{x} --> |YES| 38:task:(Review images)
37:exclusivegateway:{x} --> |NO| 39:task:(Use smartphone photos)
38:task:(Review images) --> 40:exclusivegateway:{x}
39:task:(Use smartphone photos) --> 40:exclusivegateway:{x}
40:exclusivegateway:{x} --> |YES| 41:task:(Prepare for surgery)
40:exclusivegateway:{x} --> |NO| 42:task:(Apply cast)
42:task:(Apply cast) --> 43:task:(Instruct patient to return next day)
43:task:(Instruct patient to return next day) --> 44:task:(Require new CD from radiology)
44:task:(Require new CD from radiology) --> 45:task:(Issue pain medication prescription)
45:task:(Issue pain medication prescription) --> 46:task:("Issue Sick note (4 weeks)")
46:task:("Issue Sick note (4 weeks)") --> 47:task:("Visits radiology again (08:00)")
47:task:("Visits radiology again (08:00)") --> 48:task:(Requests new CD)
48:task:(Requests new CD) --> 49:task:(Travels to hospital again)
49:task:(Travels to hospital again) --> 50:subprocess:(Re-evaluation)
50:subprocess:(Re-evaluation) --> 51:task:(Patient waits again)
51:task:(Patient waits again) --> 52:task:(Personal activities)
52:task:(Personal activities) --> 53:task:(New physician takes history again)
53:task:(New physician takes history again) --> 54:task:(CD is read successfully)
54:task:(CD is read successfully) --> 55:task:(Medication plan requested via fax)
55:task:(Medication plan requested via fax) --> 56:exclusivegateway:{x}
56:exclusivegateway:{x} --> |NO| 57:task:(Proceed to surgery)
56:exclusivegateway:{x} --> |YES| 58:task:(Suspect ligament injury)
58:task:(Suspect ligament injury) --> 59:task:(Check for previous X-rays)
59:task:(Check for previous X-rays) --> 60:exclusivegateway:{x}
60:exclusivegateway:{x} --> |YES| 61:task:(Compare)
60:exclusivegateway:{x} --> |NO| 62:task:(Order MRI)
61:task:(Compare) --> 63:subprocess:(MRI)
62:task:(Order MRI) --> 63:subprocess:(MRI)
63:subprocess:(MRI) --> 64:task:(Register patient)
64:task:(Register patient) --> 65:task:(Collect history and allergies again)
65:task:(Collect history and allergies again) --> 66:task:(Perform MRI)
66:task:(Perform MRI) --> 67:task:(Radiologist evaluates images)
67:task:(Radiologist evaluates images) --> 68:exclusivegateway:{x}
68:exclusivegateway:{x} --> |YES| 69:task:(Modify surgery plan)
68:exclusivegateway:{x} --> |NO| 70:task:(Confirm old injury)
69:task:(Modify surgery plan) --> 71:task:(Radiologist informs trauma consultant)
70:task:(Confirm old injury) --> 71:task:(Radiologist informs trauma consultant)
71:task:(Radiologist informs trauma consultant) --> 72:task:(Patient seen same day)
72:task:(Patient seen same day) --> 73:task:(Surgery date scheduled)
73:task:(Surgery date scheduled) --> 74:subprocess:(Preoperative Assessment)
74:subprocess:(Preoperative Assessment) --> 75:task:(Collect Medical history)
75:task:(Collect Medical history) --> 76:task:(Collect Medication)
76:task:(Collect Medication) --> 77:task:(Collect Allergies)
77:task:(Collect Allergies) --> 78:task:(Provide anesthesia consent documentation)
78:task:(Provide anesthesia consent documentation) --> 79:task:(Admission to ward)
79:task:(Admission to ward) --> 80:task:(Collect medical data again)
80:task:(Collect medical data again) --> 81:subprocess:(Preoperative Issue)
81:subprocess:(Preoperative Issue) --> 82:task:(Ward doctor searches for consent form)
82:task:(Ward doctor searches for consent form) --> 83:exclusivegateway:{x}
83:exclusivegateway:{x} --> |YES| 85:subprocess:(Anesthesia Complication)
83:exclusivegateway:{x} --> |NO| 84:exclusivegateway:{x}
84:exclusivegateway:{x} --> |YES| 85:subprocess:(Anesthesia Complication)
84:exclusivegateway:{x} --> |NO| 26:endevent:(((endevent)))
85:subprocess:(Anesthesia Complication) --> 86:task:(Local anesthetic administered)
86:task:(Local anesthetic administered) --> 87:exclusivegateway:{x}
87:exclusivegateway:{x} --> |NO| 89:task:(Surgery performed successfully)
87:exclusivegateway:{x} --> |YES| 88:task:(Anaphylactic shock)
88:task:(Anaphylactic shock) --> 89:task:(Surgery performed successfully)
89:task:(Surgery performed successfully) --> 90:subprocess:(Discharge)
90:subprocess:(Discharge) --> 91:task:(One night ICU)
91:task:(One night ICU) --> 92:task:(One night normal ward)
92:task:(One night normal ward) --> 93:task:(Issue allergy card)
93:task:(Issue allergy card) --> 94:task:(Provide discharge instructions)
94:task:(Provide discharge instructions) --> 95:exclusivegateway:{x}
95:exclusivegateway:{x} --> |YES| 97:subprocess:(Postoperative Treatment)
95:exclusivegateway:{x} --> |NO| 96:task:(Send to family doctor by mail)
96:task:(Send to family doctor by mail) --> 97:subprocess:(Postoperative Treatment)
97:subprocess:(Postoperative Treatment) --> 98:task:(Wound checks)
98:task:(Wound checks) --> 99:task:(Suture removal)
99:task:(Suture removal) --> 100:task:(Issue prescriptions)
100:task:(Issue prescriptions) --> 101:subprocess:(Follow-Up Issues)
101:subprocess:(Follow-Up Issues) --> 102:exclusivegateway:{x}
102:exclusivegateway:{x} --> |YES| 103:task:(Visit pharmacy)
102:exclusivegateway:{x} --> |NO| 104:task:(Buy OTC medication)
103:task:(Visit pharmacy) --> 105:subprocess:(Physiotherapy Search)
104:task:(Buy OTC medication) --> 105:subprocess:(Physiotherapy Search)
105:subprocess:(Physiotherapy Search) --> 106:task:(Search physiotherapist online)
106:task:(Search physiotherapist online) --> 107:task:(Multiple rejections)
107:task:(Multiple rejections) --> 108:exclusivegateway:{x}
108:exclusivegateway:{x} --> |NO| 106:task:(Search physiotherapist online)
108:exclusivegateway:{x} --> |YES| 109:task:("Schedule appointment (4 weeks later)")
109:task:("Schedule appointment (4 weeks later)") --> 110:subprocess:(First Physiotherapy Session)
110:subprocess:(First Physiotherapy Session) --> 111:task:(Physiotherapist requests aftercare plan)
111:task:(Physiotherapist requests aftercare plan) --> 112:exclusivegateway:{x}
112:exclusivegateway:{x} --> |YES| 113:task:(Start therapy normally)
112:exclusivegateway:{x} --> |NO| 114:task:(Therapy starts without plan)
113:task:(Start therapy normally) --> 26:endevent:(((endevent)))
114:task:(Therapy starts without plan) --> 26:endevent:(((endevent)))
9:task:(Diagnose bruise only) --> 26:endevent:(((endevent)))
41:task:(Prepare for surgery) --> 57:task:(Proceed to surgery)
57:task:(Proceed to surgery) --> 89:task:(Surgery performed successfully)